SPIN Flight Controller: MPU9250_API Class Reference
MPU9250_API Class Reference
#include <MPU9250_API.h>
Public Member Functions
float pitch ()
float yaw ()
float roll ()
float accelerationX ()
float accelerationY ()
float accelerationZ ()
float gyroX ()
float gyroY ()
float gyroZ ()
float magX ()
float magY ()
float magZ ()
Public Member Functions inherited from IMU
virtual float pitch ()
virtual float yaw ()
virtual float roll ()
virtual int16_t accelerationX ()
virtual int16_t accelerationY ()
virtual int16_t accelerationZ ()
virtual int16_t gyroX ()
virtual int16_t gyroY ()
virtual int16_t gyroZ ()
virtual void setup ()
virtual void calibrate ()
Static Public Member Functions
static MPU9250_API & getInstance ()
Private Member Functions
MPU9250_API ()
void readSensorData ()
Static Private Attributes
static MPU9250 sensor
Constructor & Destructor Documentation
MPU9250_API()
MPU9250_API::MPU9250_API () private
{
  byte c = sensor.readByte(MPU9250_ADDRESS, WHO_AM_I_MPU9250);
  if (c == 0x71) {
    sensor.MPU9250SelfTest(sensor.selfTest);
    // Calibrate gyro and accelerometers, load biases in bias registers
    sensor.calibrateMPU9250(sensor.gyroBias, sensor.accelBias);
    sensor.initMPU9250();
    byte d = sensor.readByte(AK8963_ADDRESS, WHO_AM_I_AK8963);
    if (d != 0x48) {
      // Communication failed, stop here
      Serial.println(F("Communication failed, abort!"));
      Serial.flush();
      abort();
    }
    // Get magnetometer calibration from AK8963 ROM
    sensor.initAK8963(sensor.factoryMagCalibration);
    // Get sensor resolutions, only need to do this once
    sensor.getAres();
    sensor.getGres();
    sensor.getMres();
  } else {
    Serial.print("Could not connect to MPU9250: 0x");
    Serial.println(c, HEX);
    // Communication failed, stop here
    Serial.println(F("Communication failed, abort!"));
    Serial.flush();
    abort();
  }
}
References MPU9250_ADDRESS, and sensor.
Member Function Documentation
accelerationX()
float MPU9250_API::accelerationX () virtual
Reimplemented from IMU.
{
  readSensorData();
  return sensor.ax;
}
References readSensorData(), and sensor.
accelerationY()
float MPU9250_API::accelerationY () virtual
Reimplemented from IMU.
{
  readSensorData();
  return sensor.ay;
}
References readSensorData(), and sensor.
accelerationZ()
float MPU9250_API::accelerationZ () virtual
Reimplemented from IMU.
{
  readSensorData();
  return sensor.az;
}
References readSensorData(), and sensor.
getInstance()
static MPU9250_API & MPU9250_API::getInstance () static
{
  static MPU9250_API instance;
  return instance;
}
gyroX()
float MPU9250_API::gyroX () virtual
Reimplemented from IMU.
{
  readSensorData();
  return sensor.gx;
}
References readSensorData(), and sensor.
gyroY()
float MPU9250_API::gyroY () virtual
Reimplemented from IMU.
{
  readSensorData();
  return sensor.gy;
}
References readSensorData(), and sensor.
gyroZ()
float MPU9250_API::gyroZ () virtual
Reimplemented from IMU.
{
  readSensorData();
  return sensor.gz;
}
References readSensorData(), and sensor.
magX()
float MPU9250_API::magX ()
{
  readSensorData();
  return sensor.mx;
}
References readSensorData(), and sensor.
magY()
float MPU9250_API::magY ()
{
  readSensorData();
  return sensor.my;
}
References readSensorData(), and sensor.
magZ()
float MPU9250_API::magZ ()
{
  readSensorData();
  return sensor.mz;
}
References readSensorData(), and sensor.
pitch()
float MPU9250_API::pitch () virtual
Reimplemented from IMU.
{
  readSensorData();
  return sensor.pitch;
}
References readSensorData(), and sensor.
readSensorData()
void MPU9250_API::readSensorData () private
{
  sensor.readAccelData(sensor.accelCount);
  sensor.ax = (float)sensor.accelCount[0] * sensor.aRes; // - sensor.accelBias[0];
  sensor.ay = (float)sensor.accelCount[1] * sensor.aRes; // - sensor.accelBias[1];
  sensor.az = (float)sensor.accelCount[2] * sensor.aRes; // - sensor.accelBias[2];
  sensor.readGyroData(sensor.gyroCount);
  sensor.gx = (float)sensor.gyroCount[0] * sensor.gRes;
  sensor.gy = (float)sensor.gyroCount[1] * sensor.gRes;
  sensor.gz = (float)sensor.gyroCount[2] * sensor.gRes;
  sensor.readMagData(sensor.magCount);
  sensor.mx = (float)sensor.magCount[0] * sensor.mRes * sensor.factoryMagCalibration[0] - sensor.magBias[0];
  sensor.my = (float)sensor.magCount[1] * sensor.mRes * sensor.factoryMagCalibration[1] - sensor.magBias[1];
  sensor.mz = (float)sensor.magCount[2] * sensor.mRes * sensor.factoryMagCalibration[2] - sensor.magBias[2];
  sensor.updateTime();
  MahonyQuaternionUpdate(
    sensor.ax, sensor.ay, sensor.az, sensor.gx * DEG_TO_RAD,
    sensor.gy * DEG_TO_RAD, sensor.gz * DEG_TO_RAD, sensor.my,
    sensor.mx, sensor.mz, sensor.deltat);
  sensor.yaw = atan2(2.0f * (*(getQ()+1) * *(getQ()+2) + *getQ() * *(getQ()+3)), *getQ() * *getQ() + *(getQ()+1) * *(getQ()+1) - *(getQ()+2) * *(getQ()+2) - *(getQ()+3) * *(getQ()+3));
  sensor.pitch = -asin(2.0f * (*(getQ()+1) * *(getQ()+3) - *getQ() * *(getQ()+2)));
  sensor.roll = atan2(2.0f * (*getQ() * *(getQ()+1) + *(getQ()+2) * *(getQ()+3)), *getQ() * *getQ() - *(getQ()+1) * *(getQ()+1) - *(getQ()+2) * *(getQ()+2) + *(getQ()+3) * *(getQ()+3));
  sensor.pitch *= RAD_TO_DEG;
  sensor.yaw *= RAD_TO_DEG;
  sensor.yaw -= 5;
  sensor.roll *= RAD_TO_DEG;
}
References sensor.
roll()
float MPU9250_API::roll () virtual
Reimplemented from IMU.
{
  readSensorData();
  return sensor.roll;
}
References readSensorData(), and sensor.
yaw()
float MPU9250_API::yaw () virtual
Reimplemented from IMU.
                       {
  readSensorData();
  return sensor.yaw;
}
References readSensorData(), and sensor.
Member Data Documentation
sensor
MPU9250 MPU9250_API::sensor static private
The documentation for this class was generated from the following files:
experimental_libraries/MPU9250_API.h
experimental_libraries/MPU9250_API.cpp