SPIN Flight Controller: BMP3XX_API Class Reference
BMP3XX_API Class Reference
#include <bmp3xx_api.h>
Public Member Functions
int32_t altitude_cm ()
int32_t pressure ()
int16_t temperature ()
int32_t aglCM ()
int32_t getGroundLevelCM ()
void setup ()
void calibrate ()
Public Member Functions inherited from Altimeter
virtual int32_t altitude_cm ()
float altitude ()
virtual int32_t aglCM ()
float agl ()
virtual int32_t pressure ()
virtual int16_t temperature ()
virtual int32_t getGroundLevelCM ()
virtual void setup ()
virtual void calibrate ()
Static Public Member Functions
static BMP3XX_API & getInstance ()
Private Member Functions
BMP3XX_API ()
void setGroundLevel ()
void readSensorData ()
Private Attributes
unsigned long last_sensor_read = 0
int32_t cached_altitude_cm
int32_t ground_level = 0
bool broken_connection
Static Private Attributes
static Adafruit_BMP3XX sensor
Constructor & Destructor Documentation
BMP3XX_API()
BMP3XX_API::BMP3XX_API () private
Construct a new BMP3XX_API object.
Private constructor used to create static object for singleton design pattern.
Author
themicp
{}
Member Function Documentation
aglCM()
int32_t BMP3XX_API::aglCM () virtual
Get Altitude in centimeters.
Returns the Altitude in centimeters.
The altitude can be computed by the pressure or the GPS.
The altitude is realtive to ground level.
See also
Altimeter
Example Code:
BMP3XX_API& alt = BMP3XX_API::getInstance();
...
Serial.println(alt.aglCM());
Returns
int32_t Altitude from reference point.
Author
themicp
Reimplemented from Altimeter.
{
  return altitude_cm() - ground_level;
}
References altitude_cm(), and ground_level.
altitude_cm()
int32_t BMP3XX_API::altitude_cm () virtual
Get Altitude in centimeters.
Returns the Altitude in centimeters.
The altitude can be computed by the pressure or the GPS.
See also
Altimeter
Example Code:
BMP3XX_API& alt = BMP3XX_API::getInstance();
...
Serial.println(alt.altitude_cm());
Returns
int32_t Altitude from reference point.
Author
themicp
Reimplemented from Altimeter.
{
  readSensorData();
  return cached_altitude_cm;
}
References cached_altitude_cm, and readSensorData().
calibrate()
void BMP3XX_API::calibrate () virtual
Calibrate altimeter.
Altimeters need to be calibrated from data stored in persistend storage.
Author
themicp
Reimplemented from Altimeter.
{
  sensor.setPressureOversampling(BMP3_OVERSAMPLING_16X);
  sensor.setIIRFilterCoeff(BMP3_IIR_FILTER_COEFF_7);
  sensor.setOutputDataRate(BMP3_ODR_100_HZ);
  // TODO: use something better than a constant here
  while (sensor.readAltitude(SEALEVELPRESSURE_HPA) > 1700) {
    delay(100);
  }
  delay(1000); // TODO: refine the value. New BMP needed more time
  setGroundLevel();
}
References SEALEVELPRESSURE_HPA, sensor, and setGroundLevel().
getGroundLevelCM()
int32_t BMP3XX_API::getGroundLevelCM () virtual
Get the Ground Level height.
Returns
int32_t Ground level height.
Author
themicp
Reimplemented from Altimeter.
{
  return ground_level;
}
References ground_level.
getInstance()
BMP3XX_API & BMP3XX_API::getInstance () static
{
  static BMP3XX_API instance;
  return instance;
}
pressure()
int32_t BMP3XX_API::pressure () virtual
Get Pressure in Pascal.
Returns the pressure in Pascal.
See also
Altimeter
Example Code:
BMP3XX_API& alt = BMP3XX_API::getInstance();
...
Serial.println(alt.pressure());
Returns
int32_t Pressure from last reading.
Author
themicp
Reimplemented from Altimeter.
{
  return sensor.pressure;
}
References sensor.
readSensorData()
void BMP3XX_API::readSensorData () private
Reads the latest data from the serial.
Clear the GPS buffer and read the last data available from the GPS module.
Author
themicp
{
  if (millis() - last_sensor_read < 1000/BMP_REFRESH_RATE || broken_connection) {
    return;
  }
  Wire.begin();
  Wire.beginTransmission(BMP3XX_DEFAULT_ADDRESS);
  if (Wire.endTransmission() != 0) {
    broken_connection = true;
    return;
  }
  int32_t reading = sensor.readAltitude(SEALEVELPRESSURE_HPA) * 100;
  if (abs(reading - cached_altitude_cm) >= MAX_ALTITUDE_STEP) {
    // Ignore reading if difference is extreme. Probably problem with the sensor.
    return;
  }
  cached_altitude_cm = sensor.readAltitude(SEALEVELPRESSURE_HPA) * 100;
  last_sensor_read = millis();
}
References BMP_REFRESH_RATE, broken_connection, cached_altitude_cm, last_sensor_read, MAX_ALTITUDE_STEP, SEALEVELPRESSURE_HPA, and sensor.
setGroundLevel()
void BMP3XX_API::setGroundLevel () private virtual
Reimplemented from Altimeter.
{
  ground_level = altitude_cm();
}
References altitude_cm(), and ground_level.
setup()
void BMP3XX_API::setup () virtual
Setup the Altimeter module.
Initialize the setup process of the altimeter module.
Author
themicp
Reimplemented from Altimeter.
                       {
  if (!sensor.begin()) {
    while(1); //Freeze
  }
}
References sensor.
temperature()
int16_t BMP3XX_API::temperature () virtual
Get Temperature in Celcius * 100.
Returns the temperature in celcius * 100.
See also
Altimeter
Example Code:
BMP3XX_API& alt = BMP3XX_API::getInstance();
...
Serial.println(alt.temperature());
Returns
int16_t Temperature from last reading.
Author
themicp
Reimplemented from Altimeter.
{
  return sensor.temperature * 100;
}
References sensor.
Member Data Documentation
broken_connection
bool BMP3XX_API::broken_connection private
Checks if communication protocol failed.
cached_altitude_cm
int32_t BMP3XX_API::cached_altitude_cm private
ground_level
int32_t BMP3XX_API::ground_level = 0 private
Reference ground level.
last_sensor_read
unsigned long BMP3XX_API::last_sensor_read = 0 private
Last read data time.
Ensure data is read every (1000/BMP_REFRESH_RATE)s.
sensor
Adafruit_BMP3XX BMP3XX_API::sensor static private
The documentation for this class was generated from the following files:
libraries/bmp3xx_api.h
libraries/bmp3xx_api.cpp