SPIN Flight Controller: BNO055_API Class Reference
BNO055_API Class Reference
#include <bno055_api.h>
Public Member Functions
float pitch ()
float yaw ()
float roll ()
int16_t accelerationX ()
int16_t accelerationY ()
int16_t accelerationZ ()
int16_t gyroX ()
int16_t gyroY ()
int16_t gyroZ ()
float magX ()
float magY ()
float magZ ()
void setup ()
void calibrate ()
virtual float pitch ()
virtual float yaw ()
virtual float roll ()
virtual int16_t accelerationX ()
virtual int16_t accelerationY ()
virtual int16_t accelerationZ ()
virtual int16_t gyroX ()
virtual int16_t gyroY ()
virtual int16_t gyroZ ()
virtual void setup ()
virtual void calibrate ()
Static Public Member Functions
static BNO055_API & getInstance ()
Private Member Functions
BNO055_API ()
void readSensorData ()
Private Attributes
unsigned long last_read = 0
imu::Vector< 3 > euler
imu::Vector< 3 > acc
imu::Vector< 3 > gyro
imu::Vector< 3 > mag
Static Private Attributes
static Adafruit_BNO055 sensor
Constructor & Destructor Documentation
BNO055_API()
BNO055_API::BNO055_API () private
{}
Member Function Documentation
accelerationX()
int16_t BNO055_API::accelerationX () virtual
Reimplemented from IMU.
{
  readSensorData();
  return acc.x() * 100;
}
References acc, and readSensorData().
accelerationY()
int16_t BNO055_API::accelerationY () virtual
Reimplemented from IMU.
{
  readSensorData();
  return acc.y() * 100;
}
References acc, and readSensorData().
accelerationZ()
int16_t BNO055_API::accelerationZ () virtual
Reimplemented from IMU.
{
  readSensorData();
  return acc.z() * 100;
}
References acc, and readSensorData().
calibrate()
void BNO055_API::calibrate () virtual
Reimplemented from IMU.
{
  uint8_t system, gyro, accel, mag;
  system = gyro = accel = mag = 0;
  while (sensor.isFullyCalibrated()) {}
}
References gyro, mag, and sensor.
getInstance()
BNO055_API & BNO055_API::getInstance () static
{
  static BNO055_API instance;
  return instance;
}
gyroX()
int16_t BNO055_API::gyroX () virtual
Reimplemented from IMU.
{
  readSensorData();
  return gyro.x() * (180 / M_PI);
}
References gyro, and readSensorData().
gyroY()
int16_t BNO055_API::gyroY () virtual
Reimplemented from IMU.
{
  readSensorData();
  return gyro.y() * (180 / M_PI);
}
References gyro, and readSensorData().
gyroZ()
int16_t BNO055_API::gyroZ () virtual
Reimplemented from IMU.
{
  readSensorData();
  return gyro.z() * (180 / M_PI);
}
References gyro, and readSensorData().
magX()
float BNO055_API::magX ()
                       {
  readSensorData();
  return mag.x();
}
References mag, and readSensorData().
magY()
float BNO055_API::magY ()
                       {
  readSensorData();
  return mag.y();
}
References mag, and readSensorData().
magZ()
float BNO055_API::magZ ()
                       {
  readSensorData();
  return mag.z();
}
References mag, and readSensorData().
pitch()
float BNO055_API::pitch () virtual
Reimplemented from IMU.
{
  readSensorData();
  return euler.y();
}
References euler, and readSensorData().
readSensorData()
void BNO055_API::readSensorData () private
{
  // TODO: fix units
  if (millis() - last_read < READ_INTERVAL) {
    return;
  }
  euler = sensor.getVector(Adafruit_BNO055::VECTOR_EULER);
  acc = sensor.getVector(Adafruit_BNO055::VECTOR_ACCELEROMETER);
  gyro = sensor.getVector(Adafruit_BNO055::VECTOR_GYROSCOPE);
  mag = sensor.getVector(Adafruit_BNO055::VECTOR_MAGNETOMETER);
  last_read = millis();
}
References acc, euler, gyro, last_read, mag, READ_INTERVAL, and sensor.
roll()
float BNO055_API::roll () virtual
Reimplemented from IMU.
                       {
  readSensorData();
  return euler.z();
}
References euler, and readSensorData().
setup()
void BNO055_API::setup () virtual
Reimplemented from IMU.
                       {
  // Relative heading -- no magnetometer
  if(!sensor.begin(Adafruit_BNO055::OPERATION_MODE_ACCGYRO)) {
    while(1);
  }
  // 2G = 0, 4G = 1, 8G = 2, 16G = 3
  sensor.setAccelRange(3);
  // TODO: do we need this?
  sensor.setExtCrystalUse(true);
}
References sensor.
yaw()
float BNO055_API::yaw () virtual
Reimplemented from IMU.
                      {
  readSensorData();
  return euler.x();
}
References euler, and readSensorData().
Member Data Documentation
acc
imu::Vector<3> BNO055_API::acc private
euler
imu::Vector<3> BNO055_API::euler private
gyro
imu::Vector<3> BNO055_API::gyro private
last_read
unsigned long BNO055_API::last_read = 0 private
mag
imu::Vector<3> BNO055_API::mag private
sensor
Adafruit_BNO055 BNO055_API::sensor static private
The documentation for this class was generated from the following files:
libraries/bno055_api.h
libraries/bno055_api.cpp