SPIN Flight Controller: Adafruit_GPS_API Class Reference
Adafruit_GPS_API Class Reference
#include <adafruit_gps_api.h>
Public Member Functions
void setup ()
bool fix ()
int32_t latitude ()
int32_t longitude ()
float altitude ()
int satellites ()
virtual void setup ()
virtual bool fix ()
virtual int32_t latitude ()
virtual int32_t longitude ()
virtual float altitude ()
virtual int satellites ()
Static Public Member Functions
static Adafruit_GPS_API & getInstance ()
Private Member Functions
Adafruit_GPS_API ()
void readData ()
Private Attributes
unsigned long last_read
Static Private Attributes
static Adafruit_GPS receiver
Constructor & Destructor Documentation
Adafruit_GPS_API()
Adafruit_GPS_API::Adafruit_GPS_API () private
Construct a new Adafruit_GPS_API object.
Private constructor used to create static object for singleton design pattern.
Author
themicp
{};
Member Function Documentation
altitude()
float Adafruit_GPS_API::altitude () virtual
Returns Altitude.
This function is used to return the last recorder altitude of the gps module. The value returned is in meters.
Returns
float The altitude in meters.
Author
themicp
Reimplemented from GPSReceiver.
{
  // Check if last data is updated.
  readData();
  // Return 0 if no fix.
  if (!fix())
  {
    return 0;
  }
  return receiver.altitude;
}
References fix(), readData(), and receiver.
fix()
bool Adafruit_GPS_API::fix () virtual
Checks if GPS Module has access to 3 satelites.
Each GPS modules needs direct access to 3 satelits to be able to determine its latitude and longitude.
This function returns whether the module is able to access atleast 3 satelites.
Returns
true When the GPS module has successfully "paired" to 3 satelites.
false When the GPS module has not successfully "paired" to 3 satelites.
Author
themicp
Reimplemented from GPSReceiver.
{
  // Check if last data is updated.
  readData();
  return receiver.fix;
}
References readData(), and receiver.
getInstance()
Adafruit_GPS_API & Adafruit_GPS_API::getInstance () static
{
  static Adafruit_GPS_API instance;
  return instance;
}
latitude()
int32_t Adafruit_GPS_API::latitude () virtual
Returns latitude.
This function is used to return the last recorder latitude of the gps module. The value returned is in degrees and minutes in the following format: Latitude: DDMM.MMMM (The first two characters are the degrees.)
Returns
int32_t The latitude in degress and minutes.
Author
themicp
Reimplemented from GPSReceiver.
{
  // Check if last data is updated.
  readData();
  // Return 0 if no fix.
  if (!fix())
  {
    return 0;
  }
  return receiver.latitude_fixed;
}
References fix(), readData(), and receiver.
longitude()
int32_t Adafruit_GPS_API::longitude () virtual
Returns longitude.
This function is used to return the last recorder longitude of the gps module. The value returned is in degrees and minutes in the following format: Longitude: DDDMM.MMMM (The first three characters are the degrees.)
Returns
int32_t The longitude in degress and minutes.
Author
themicp
Reimplemented from GPSReceiver.
{
  // Check if last data is updated.
  readData();
  // Return 0 if no fix.
  if (!fix())
  {
    return 0;
  }
  return receiver.longitude_fixed;
}
References fix(), readData(), and receiver.
readData()
void Adafruit_GPS_API::readData () private
Reads the latest data from the serial.
Clear the GPS buffer and read the last data available from the GPS module.
Author
themicp
{
  // Wait for 100ms between meassurments.
  if (millis() - last_read < 100) {
    return;
  }
  // Empty buffer.
  while(receiver.read());
  last_read = millis();
  // Parse data.
  if (receiver.newNMEAreceived()) {
    receiver.parse(receiver.lastNMEA());
  }
}
References last_read, and receiver.
satellites()
int Adafruit_GPS_API::satellites () virtual
Returns the number of available satelites.
Returns
int The number of satelites available to the GPS Module.
Author
themicp
Reimplemented from GPSReceiver.
{
  // Check if last data is updated.
  readData();
  return receiver.satellites;
}
References readData(), and receiver.
setup()
void Adafruit_GPS_API::setup () virtual
Setup Adafruit GPS Receiver.
Initialize the setup process of the GPS module.
The setup function does not mean that the GPS module will function normally or that it will have access to at least 3 satelites.
See also
GPSReceiver
Example Code:
Adafruit_GPS_API receiver = Adafruit_GPS_API::getInstance();
receiver.setup();
Author
themicp
Reimplemented from GPSReceiver.
{
  last_read = 0;
  receiver.begin(9600);
  // turn on GPRMC and GGA.
  receiver.sendCommand(PMTK_SET_NMEA_OUTPUT_RMCGGA);
  // Update every 1Hz.
  receiver.sendCommand(PMTK_SET_NMEA_UPDATE_1HZ);
  // Possition fix update every 1Hz.
  receiver.sendCommand(PMTK_API_SET_FIX_CTL_1HZ);
}
References last_read, and receiver.
Member Data Documentation
last_read
unsigned long Adafruit_GPS_API::last_read private
Last read data time.
Ensure data is read every 100ms.
receiver
Adafruit_GPS Adafruit_GPS_API::receiver static private
The documentation for this class was generated from the following files:
libraries/adafruit_gps_api.h
libraries/adafruit_gps_api.cpp