SPIN Flight Controller: FSM Class Reference
FSM Class Reference
#include <fsm.h>
Public Member Functions
template<size_t N>
void register_state_transitions (Transition(&transitions)[N])
void process_event (EVENT event)
void runCurrentState ()
FSM (Telemetry *telemetry, IMU *imu_sensor, Altimeter *altimeter, GPSReceiver *gps, Igniter *igniter, uint8_t *loop_frequency)
Private Member Functions
void onSetup ()
void onIDLE ()
void onCalibration ()
void onReady ()
void onLaunched ()
void onArmBackupDeployer ()
void onResetBackupDeployer ()
void onEjectionTestReady ()
void onEjectionTestEject ()
void onEjectionTestComplete ()
void onAscending ()
void onApogeeTimeout ()
void onDeployingChute ()
void onRecovering ()
Private Attributes
STATE state = STATE::SETUP
STATE state_transitions [(int) STATE::Count][(int) EVENT::Count]
Telemetry * telemetry
IMU * imu_sensor
Altimeter * altimeter
GPSReceiver * gps
Igniter * igniter
uint8_t * loop_frequency
unsigned long launch_time
unsigned long ejection_start
float max_agl = 0
Constructor & Destructor Documentation
FSM()
FSM::FSM (Telemetry * telemetry, IMU * imu_sensor, Altimeter * altimeter, GPSReceiver * gps, Igniter * igniter, uint8_t * loop_frequency)
  : telemetry(telemetry)
  , imu_sensor(imu_sensor)
  , altimeter(altimeter)
  , gps(gps)
  , igniter(igniter)
  , loop_frequency(loop_frequency)
{
  Transition flight_state_transitions[] = {
    // Ground
    Transition(STATE::SETUP, EVENT::SETUP_COMPLETE, STATE::IDLE),
    Transition(STATE::IDLE, EVENT::INIT_CALIBRATION, STATE::CALIBRATION),
    Transition(STATE::READY, EVENT::INIT_CALIBRATION, STATE::CALIBRATION),
    Transition(STATE::READY, EVENT::SET_EJECTION_TEST, STATE::EJECTION_TEST_READY),
    Transition(STATE::CALIBRATION, EVENT::CALIBRATION_COMPLETE, STATE::READY),
    Transition(STATE::READY, EVENT::START_BACKUP_COUNTDOWN, STATE::ARM_BACKUP_DEPLOYER),
    Transition(STATE::READY, EVENT::RESET_BACKUP_COUNTDOWN, STATE::RESET_BACKUP_DEPLOYER),
    Transition(STATE::ARM_BACKUP_DEPLOYER, EVENT::BACKUP_COUNTDOWN_STARTED, STATE::READY),
    Transition(STATE::RESET_BACKUP_DEPLOYER, EVENT::BACKUP_COUNTDOWN_RESETTED, STATE::READY),
    Transition(STATE::READY, EVENT::LAUNCHED, STATE::ASCENDING),
    Transition(STATE::READY, EVENT::GO_IDLE, STATE::IDLE),
    // Ejection Test
    Transition(STATE::EJECTION_TEST_READY, EVENT::TRIGGER_FTS, STATE::EJECTION_TEST_EJECT),
    Transition(STATE::EJECTION_TEST_EJECT, EVENT::CHUTE_EJECTED, STATE::EJECTION_TEST_COMPLETE),
    // Flying
    Transition(STATE::ASCENDING, EVENT::APOGEE_TIMER_TIMEOUT, STATE::APOGEE_TIMEOUT),
    Transition(STATE::ASCENDING, EVENT::INIT_CALIBRATION, STATE::CALIBRATION),
    Transition(STATE::ASCENDING, EVENT::APOGEE_DETECTED, STATE::DEPLOYING_CHUTE),
    Transition(STATE::APOGEE_TIMEOUT, EVENT::APOGEE_DETECTED, STATE::DEPLOYING_CHUTE),
    Transition(STATE::DEPLOYING_CHUTE, EVENT::CHUTE_EJECTED, STATE::RECOVERING),
    // FTS from all states except IDLE
    Transition(STATE::SETUP, EVENT::TRIGGER_FTS, STATE::DEPLOYING_CHUTE),
    Transition(STATE::CALIBRATION, EVENT::TRIGGER_FTS, STATE::DEPLOYING_CHUTE),
    Transition(STATE::READY, EVENT::TRIGGER_FTS, STATE::DEPLOYING_CHUTE),
    Transition(STATE::ASCENDING, EVENT::TRIGGER_FTS, STATE::DEPLOYING_CHUTE),
    Transition(STATE::APOGEE_TIMEOUT, EVENT::TRIGGER_FTS, STATE::DEPLOYING_CHUTE),
    Transition(STATE::RECOVERING, EVENT::TRIGGER_FTS, STATE::DEPLOYING_CHUTE)
  };
  register_state_transitions(flight_state_transitions);
}
References APOGEE_DETECTED, APOGEE_TIMEOUT, APOGEE_TIMER_TIMEOUT, ARM_BACKUP_DEPLOYER, ASCENDING, BACKUP_COUNTDOWN_RESETTED, BACKUP_COUNTDOWN_STARTED, CALIBRATION, CALIBRATION_COMPLETE, CHUTE_EJECTED, DEPLOYING_CHUTE, EJECTION_TEST_COMPLETE, EJECTION_TEST_EJECT, EJECTION_TEST_READY, GO_IDLE, IDLE, INIT_CALIBRATION, LAUNCHED, READY, RECOVERING, register_state_transitions(), RESET_BACKUP_COUNTDOWN, RESET_BACKUP_DEPLOYER, SET_EJECTION_TEST, SETUP, SETUP_COMPLETE, START_BACKUP_COUNTDOWN, and TRIGGER_FTS.
Member Function Documentation
onApogeeTimeout()
void FSM::onApogeeTimeout () private
{
  process_event(EVENT::APOGEE_DETECTED);
}
References APOGEE_DETECTED, and process_event().
onArmBackupDeployer()
void FSM::onArmBackupDeployer () private
{
  BackupDeployer::startArmCountdown();
  process_event(EVENT::BACKUP_COUNTDOWN_STARTED);
}
References BACKUP_COUNTDOWN_STARTED, process_event(), and BackupDeployer::startArmCountdown().
onAscending()
void FSM::onAscending () private
                      {
  float agl = altimeter->agl();
  if (agl > max_agl) {
    max_agl = agl;
  }
  if (max_agl - agl >= APOGEE_AGL_DIFF_THRESHOLD &&
    millis() - launch_time > BOOST_TIME * 1000) {
    process_event(EVENT::APOGEE_DETECTED);
  } else if (millis() - launch_time > TIME_TO_APOGEE * 1000) {
    process_event(EVENT::APOGEE_TIMER_TIMEOUT);
  }
  // TODO: check IMU ?
}
References Altimeter::agl(), altimeter, APOGEE_AGL_DIFF_THRESHOLD, APOGEE_DETECTED, APOGEE_TIMER_TIMEOUT, BOOST_TIME, launch_time, max_agl, process_event(), and TIME_TO_APOGEE.
onCalibration()
void FSM::onCalibration () private
{
  telemetry->send("Altimeter: calibrating..");
  altimeter->calibrate();
  telemetry->send("Altimeter: ground level set to " + String((float)altimeter->getGroundLevelCM() / 100) + "m");
  telemetry->send("IMU: calibrating..");
  imu_sensor->calibrate();
  telemetry->send("IMU: calibrated.");
  process_event(EVENT::CALIBRATION_COMPLETE);
}
References altimeter, Altimeter::calibrate(), IMU::calibrate(), CALIBRATION_COMPLETE, Altimeter::getGroundLevelCM(), imu_sensor, process_event(), Telemetry::send(), and telemetry.
onDeployingChute()
void FSM::onDeployingChute () private
{
  igniter->enable();
  if (millis() - ejection_start > EJECTION_TIMEOUT) {
    igniter->disable();
    process_event(EVENT::CHUTE_EJECTED);
    telemetry->setRadioThrottle(0);
    *loop_frequency = 10;
  }
}
References CHUTE_EJECTED, Igniter::disable(), ejection_start, EJECTION_TIMEOUT, Igniter::enable(), igniter, loop_frequency, process_event(), Telemetry::setRadioThrottle(), and telemetry.
onEjectionTestComplete()
void FSM::onEjectionTestComplete () private
{
  telemetry->setRadioThrottle(0);
  *loop_frequency = 10;
}
References loop_frequency, Telemetry::setRadioThrottle(), and telemetry.
onEjectionTestEject()
void FSM::onEjectionTestEject () private
{
  telemetry->setRadioThrottle(1000);
  *loop_frequency = 100;
  onDeployingChute();
}
References loop_frequency, onDeployingChute(), Telemetry::setRadioThrottle(), and telemetry.
onEjectionTestReady()
void FSM::onEjectionTestReady () private
{}
onIDLE()
void FSM::onIDLE () private
{}
onLaunched()
void FSM::onLaunched () private
                     {
  // TODO: not the best place to do that
  launch_time = millis();
  telemetry->setRadioThrottle(1000);
  *loop_frequency = 100;
}
References launch_time, loop_frequency, Telemetry::setRadioThrottle(), and telemetry.
onReady()
void FSM::onReady () private
                  {
  if (altimeter->agl() > LAUNCH_AGL_THRESHOLD or
      (imu_sensor->accelerationX() / GRAVITY) * -1 > LAUNCH_ACCELERATION_THRESHOLD) {
    process_event(EVENT::LAUNCHED);
  }
}
References IMU::accelerationX(), Altimeter::agl(), altimeter, GRAVITY, imu_sensor, LAUNCH_ACCELERATION_THRESHOLD, LAUNCH_AGL_THRESHOLD, LAUNCHED, and process_event().
onRecovering()
void FSM::onRecovering () private
                       {
  // TODO: celebrate
}
onResetBackupDeployer()
void FSM::onResetBackupDeployer () private
{
  BackupDeployer::resetCountdown();
  process_event(EVENT::BACKUP_COUNTDOWN_RESETTED);
}
References BACKUP_COUNTDOWN_RESETTED, process_event(), and BackupDeployer::resetCountdown().
onSetup()
void FSM::onSetup () private
                  {
  telemetry->setup();
  telemetry->send("Hello!");
  Wire.begin();
  telemetry->send("Wire begin");
  telemetry->send("Setting up IMU..");
  imu_sensor->setup();
  telemetry->send("IMU setup complete.");
  telemetry->send("Setting up Altimeter..");
  altimeter->setup();
  telemetry->send("Altimeter setup complete.");
  telemetry->send("Setting up GPS..");
  gps->setup();
  telemetry->send("GPS setup complete.");
  telemetry->send("Setting up Igniter..");
  igniter->setup();
  telemetry->send("Igniter setup complete.");
  telemetry->send("Setting up Backup Deployer..");
  BackupDeployer::setup();
  telemetry->send("Backup Deployer setup complete.");
  process_event(EVENT::SETUP_COMPLETE);
}
References altimeter, gps, igniter, imu_sensor, process_event(), Telemetry::send(), Altimeter::setup(), BackupDeployer::setup(), GPSReceiver::setup(), Igniter::setup(), IMU::setup(), Telemetry::setup(), SETUP_COMPLETE, and telemetry.
process_event()
void FSM::process_event (EVENT event)
{
  telemetry->send("FSM Event: " + event_to_str(event));
  if (state_transitions[(int)state][(int)event] != STATE::INVALID_STATE) {
    state = state_transitions[(int)state][(int)event];
    if (state == STATE::DEPLOYING_CHUTE || state == STATE::EJECTION_TEST_EJECT) {
      ejection_start = millis();
    }
    if (event == EVENT::LAUNCHED) {
      onLaunched();
    }
  } else {
    telemetry->send("No transition from state " + state_to_str(state) + " with event " + event_to_str(event));
  }
}
References DEPLOYING_CHUTE, ejection_start, EJECTION_TEST_EJECT, event_to_str(), INVALID_STATE, LAUNCHED, onLaunched(), Telemetry::send(), state, state_to_str(), state_transitions, and telemetry.
register_state_transitions()
template<size_t N> void FSM::register_state_transitions (Transition(&) transitions[N])
{
  for (int i = 0; i < (int)STATE::Count; ++i) {
    for (int j = 0; j < (int)EVENT::Count; ++j) {
      state_transitions[i][j] = STATE::INVALID_STATE;
    }
  }
  for (int i = 0; i < N; ++i) {
    state_transitions[(int)transitions[i].src_state][(int)transitions[i].event] = transitions[i].dst_state;
  }
}
References Count, INVALID_STATE, and state_transitions.
runCurrentState()
void FSM::runCurrentState ()
{
  TelemetryMessage message;
  TelemetryMessagePayload payload;
  message.type = MESSAGE_TYPE::TELEMETRY;
  message.met = millis();
  message.free_memory_kb = freeMemory()/1000;
  message.battery_voltage_mv = get_battery_voltage_mv();
  message.state = state;
#if SD_LOGS
  message.sd_logs_enabled = true;
#else
  message.sd_logs_enabled = false;
#endif
  message.selected_igniter = IGNITER;
  if (state != STATE::SETUP and state != STATE::IDLE and state != STATE::CALIBRATION) {
    payload.agl_cm = altimeter->aglCM();
    payload.pressure = altimeter->pressure();
    payload.temperature = altimeter->temperature();
    payload.acceleration_x = imu_sensor->accelerationX();
    payload.acceleration_y = imu_sensor->accelerationY();
    payload.acceleration_z = imu_sensor->accelerationZ();
    payload.gyroscope_x = imu_sensor->gyroX();
    payload.gyroscope_y = imu_sensor->gyroY();
    payload.gyroscope_z = imu_sensor->gyroZ();
    payload.gps_fix = gps->fix();
    payload.gps_satellites = gps->satellites();
    payload.gps_latitude = gps->latitude();
    payload.gps_longitude = gps->longitude();
    message.payload = payload;
  }
  telemetry->send(message);
  switch (state) {
    case STATE::SETUP:
      onSetup();
      break;
    case STATE::IDLE:
      onIDLE();
      break;
    case STATE::CALIBRATION:
      onCalibration();
      break;
    case STATE::READY:
      onReady();
      break;
    case STATE::ARM_BACKUP_DEPLOYER:
      onArmBackupDeployer();
      break;
    case STATE::RESET_BACKUP_DEPLOYER:
      onResetBackupDeployer();
      break;
    case STATE::EJECTION_TEST_READY:
      onEjectionTestReady();
      break;
    case STATE::EJECTION_TEST_EJECT:
      onEjectionTestEject();
      break;
    case STATE::EJECTION_TEST_COMPLETE:
      onEjectionTestComplete();
      break;
    case STATE::ASCENDING:
      onAscending();
      break;
    case STATE::APOGEE_TIMEOUT:
      onApogeeTimeout();
      break;
    case STATE::DEPLOYING_CHUTE:
      onDeployingChute();
      break;
    case STATE::RECOVERING:
      onRecovering();
      break;
  }
}
References TelemetryMessagePayload::acceleration_x, TelemetryMessagePayload::acceleration_y, TelemetryMessagePayload::acceleration_z, IMU::accelerationX(), IMU::accelerationY(), IMU::accelerationZ(), TelemetryMessagePayload::agl_cm, Altimeter::aglCM(), altimeter, APOGEE_TIMEOUT, ARM_BACKUP_DEPLOYER, ASCENDING, TelemetryMessage::battery_voltage_mv, CALIBRATION, DEPLOYING_CHUTE, EJECTION_TEST_COMPLETE, EJECTION_TEST_EJECT, EJECTION_TEST_READY, GPSReceiver::fix(), TelemetryMessage::free_memory_kb, freeMemory(), get_battery_voltage_mv(), gps, TelemetryMessagePayload::gps_fix, TelemetryMessagePayload::gps_latitude, TelemetryMessagePayload::gps_longitude, TelemetryMessagePayload::gps_satellites, TelemetryMessagePayload::gyroscope_x, TelemetryMessagePayload::gyroscope_y, TelemetryMessagePayload::gyroscope_z, IMU::gyroX(), IMU::gyroY(), IMU::gyroZ(), IDLE, IGNITER, imu_sensor, GPSReceiver::latitude(), GPSReceiver::longitude(), TelemetryMessage::met, onApogeeTimeout(), onArmBackupDeployer(), onAscending(), onCalibration(), onDeployingChute(), onEjectionTestComplete(), onEjectionTestEject(), onEjectionTestReady(), onIDLE(), onReady(), onRecovering(), onResetBackupDeployer(), onSetup(), TelemetryMessage::payload, Altimeter::pressure(), TelemetryMessagePayload::pressure, READY, RECOVERING, RESET_BACKUP_DEPLOYER, GPSReceiver::satellites(), TelemetryMessage::sd_logs_enabled, TelemetryMessage::selected_igniter, Telemetry::send(), SETUP, state, TelemetryMessage::state, telemetry, TELEMETRY, Altimeter::temperature(), TelemetryMessagePayload::temperature, and TelemetryMessage::type.
Member Data Documentation
altimeter
Altimeter* FSM::altimeter private
ejection_start
unsigned long FSM::ejection_start private
gps
GPSReceiver* FSM::gps private
igniter
Igniter* FSM::igniter private
imu_sensor
IMU* FSM::imu_sensor private
launch_time
unsigned long FSM::launch_time private
loop_frequency
uint8_t* FSM::loop_frequency private
max_agl
float FSM::max_agl = 0 private
state
STATE FSM::state = STATE::SETUP private
state_transitions
STATE FSM::state_transitions[(int) STATE::Count][(int) EVENT::Count] private
telemetry
Telemetry* FSM::telemetry private
The documentation for this class was generated from the following files:
libraries/fsm.h
libraries/fsm.cpp