SPIN Flight Controller: LSM9DS1_API Class Reference
LSM9DS1_API Class Reference
#include <LSM9DS1_API.h>
Public Member Functions
float pitch ()
float yaw ()
float roll ()
float accelerationX ()
float accelerationY ()
float accelerationZ ()
float gyroX ()
float gyroY ()
float gyroZ ()
void readSensorData ()
float pitch ()
float yaw ()
float roll ()
int16_t accelerationX ()
int16_t accelerationY ()
int16_t accelerationZ ()
int16_t gyroX ()
int16_t gyroY ()
int16_t gyroZ ()
float magX ()
float magY ()
float magZ ()
void setup ()
void calibrate ()
virtual float pitch ()
virtual float yaw ()
virtual float roll ()
virtual int16_t accelerationX ()
virtual int16_t accelerationY ()
virtual int16_t accelerationZ ()
virtual int16_t gyroX ()
virtual int16_t gyroY ()
virtual int16_t gyroZ ()
virtual void setup ()
virtual void calibrate ()
Static Public Member Functions
static LSM9DS1_API & getInstance ()
static LSM9DS1_API & getInstance ()
Private Member Functions
LSM9DS1_API ()
LSM9DS1_API ()
void readSensorData ()
Private Attributes
unsigned long last_read = 0
sensors_event_t acc
sensors_event_t mag
sensors_event_t gyro
sensors_event_t temp
bool broken_connection = false
Static Private Attributes
static Adafruit_LSM9DS1 sensor = Adafruit_LSM9DS1()
Constructor & Destructor Documentation
LSM9DS1_API() [1/2]
LSM9DS1_API::LSM9DS1_API () private
{
  if (!sensor.begin()) {
    Serial.print(F("No LSM9DS1 detected ... Check your wiring or I2C ADDR!"));
    while(1);
  }
  filter.begin(25);
  sensor.setupAccel(sensor.LSM9DS1_ACCELRANGE_2G);
  //lsm.setupAccel(lsm.LSM9DS0_ACCELRANGE_4G);
  //lsm.setupAccel(lsm.LSM9DS0_ACCELRANGE_6G);
  //lsm.setupAccel(lsm.LSM9DS0_ACCELRANGE_8G);
  //lsm.setupAccel(lsm.LSM9DS0_ACCELRANGE_16G);
  // 2.) Set the magnetometer sensitivity
  sensor.setupMag(sensor.LSM9DS1_MAGGAIN_4GAUSS);
  //lsm.setupMag(lsm.LSM9DS0_MAGGAIN_4GAUSS);
  //lsm.setupMag(lsm.LSM9DS0_MAGGAIN_8GAUSS);
  //lsm.setupMag(lsm.LSM9DS0_MAGGAIN_12GAUSS);
  // 3.) Setup the gyroscope
  sensor.setupGyro(sensor.LSM9DS1_GYROSCALE_245DPS);
  //lsm.setupGyro(lsm.LSM9DS0_GYROSCALE_500DPS);
  //lsm.setupGyro(lsm.LSM9DS0_GYROSCALE_2000DPS);
}
References filter, and sensor.
LSM9DS1_API() [2/2]
LSM9DS1_API::LSM9DS1_API () private
Member Function Documentation
accelerationX() [1/2]
int16_t LSM9DS1_API::accelerationX () virtual
Reimplemented from IMU.
{
  return 0;
}
accelerationX() [2/2]
int16_t LSM9DS1_API::accelerationX () virtual
Reimplemented from IMU.
accelerationY() [1/2]
int16_t LSM9DS1_API::accelerationY () virtual
Reimplemented from IMU.
{
  return 0;
}
accelerationY() [2/2]
int16_t LSM9DS1_API::accelerationY () virtual
Reimplemented from IMU.
accelerationZ() [1/2]
int16_t LSM9DS1_API::accelerationZ () virtual
Reimplemented from IMU.
{
  return 0;
}
accelerationZ() [2/2]
int16_t LSM9DS1_API::accelerationZ () virtual
Reimplemented from IMU.
calibrate()
void LSM9DS1_API::calibrate () virtual
Reimplemented from IMU.
{
  // noop -- already calibrated
}
getInstance() [1/2]
LSM9DS1_API & LSM9DS1_API::getInstance () static
{
  static LSM9DS1_API instance;
  return instance;
}
getInstance() [2/2]
static LSM9DS1_API & LSM9DS1_API::getInstance () static
gyroX() [1/2]
int16_t LSM9DS1_API::gyroX () virtual
Reimplemented from IMU.
{
  return 0;
}
gyroX() [2/2]
int16_t LSM9DS1_API::gyroX () virtual
Reimplemented from IMU.
gyroY() [1/2]
int16_t LSM9DS1_API::gyroY () virtual
Reimplemented from IMU.
{
  return 0;
}
gyroY() [2/2]
int16_t LSM9DS1_API::gyroY () virtual
Reimplemented from IMU.
gyroZ() [1/2]
int16_t LSM9DS1_API::gyroZ () virtual
Reimplemented from IMU.
{
  return 0;
}
gyroZ() [2/2]
int16_t LSM9DS1_API::gyroZ () virtual
Reimplemented from IMU.
magX()
float LSM9DS1_API::magX ()
{
  readSensorData();
  return mag.magnetic.y;
}
References mag, and readSensorData().
magY()
float LSM9DS1_API::magY ()
{
  readSensorData();
  return mag.magnetic.x;
}
References mag, and readSensorData().
magZ()
float LSM9DS1_API::magZ ()
{
  readSensorData();
  return mag.magnetic.z;
}
References mag, and readSensorData().
pitch() [1/2]
float LSM9DS1_API::pitch () virtual
Reimplemented from IMU.
{
  return filter.getPitch();
}
References filter.
pitch() [2/2]
float LSM9DS1_API::pitch () virtual
Reimplemented from IMU.
readSensorData() [1/2]
void LSM9DS1_API::readSensorData ()
{
  sensors_event_t a, m, g, temp;
  sensor.getEvent(&a, &m, &g, &temp);
  float ax = a.acceleration.x;
  float ay = a.acceleration.y;
  float az = a.acceleration.z;
  float mx = m.magnetic.x;
  float my = m.magnetic.y;
  float mz = m.magnetic.z;
  float gx = g.gyro.x;
  float gy = g.gyro.y;
  float gz = g.gyro.z;
  MadgwickQuaternionUpdate(-ax, ay, az, gx*PI/180.0f, -gy*PI/180.0f, -gz*PI/180.0f,  my,  -mx, mz);
  float a12 =   2.0f * (q[1] * q[2] + q[0] * q[3]);
  float a22 =   q[0] * q[0] + q[1] * q[1] - q[2] * q[2] - q[3] * q[3];
  float a31 =   2.0f * (q[0] * q[1] + q[2] * q[3]);
  float a32 =   2.0f * (q[1] * q[3] - q[0] * q[2]);
  float a33 =   q[0] * q[0] - q[1] * q[1] - q[2] * q[2] + q[3] * q[3];
  float pitch = -asinf(a32);
  float roll  = atan2f(a31, a33);
  float yaw   = atan2f(a12, a22);
  pitch *= 180.0f / PI;
  yaw   *= 180.0f / PI;
  yaw   += 13.8f; // Declination at Danville, California is 13 degrees 48 minutes and 47 seconds on 2014-04-04
  if(yaw < 0) yaw   += 360.0f;
  roll  *= 180.0f / PI;
  Serial.print("Yaw, Pitch, Roll: ");
  Serial.print(yaw, 2);
  Serial.print(", ");
  Serial.print(pitch, 2);
  Serial.print(", ");
  Serial.println(roll, 2);
}
References MadgwickQuaternionUpdate(), pitch(), q, roll(), sensor, temp, and yaw().
readSensorData() [2/2]
void LSM9DS1_API::readSensorData () private
roll() [1/2]
float LSM9DS1_API::roll () virtual
Reimplemented from IMU.
{
  return filter.getRoll();
}
References filter.
roll() [2/2]
float LSM9DS1_API::roll () virtual
Reimplemented from IMU.
setup()
void LSM9DS1_API::setup () virtual
Reimplemented from IMU.
{
  // Relative heading -- no magnetometer
  if (!sensor.begin()) {
    while(1);
  }
  sensor.setupAccel(sensor.LSM9DS1_ACCELRANGE_16G, sensor.LSM9DS1_ACCELDATARATE_119HZ);
  sensor.setupMag(sensor.LSM9DS1_MAGGAIN_4GAUSS);
  sensor.setupGyro(sensor.LSM9DS1_GYROSCALE_500DPS);
}
References sensor.
yaw() [1/2]
float LSM9DS1_API::yaw () virtual
Reimplemented from IMU.
                       {
  return filter.getYaw();
}
References filter.
yaw() [2/2]
float LSM9DS1_API::yaw () virtual
Reimplemented from IMU.
Member Data Documentation
acc
sensors_event_t LSM9DS1_API::acc private
broken_connection
bool LSM9DS1_API::broken_connection = false private
gyro
sensors_event_t LSM9DS1_API::gyro private
last_read
unsigned long LSM9DS1_API::last_read = 0 private
mag
sensors_event_t LSM9DS1_API::mag private
sensor
static Adafruit_LSM9DS1 LSM9DS1_API::sensor = Adafruit_LSM9DS1() static private
temp
sensors_event_t LSM9DS1_API::temp private
The documentation for this class was generated from the following files:
experimental_libraries/LSM9DS1_API.h
libraries/lsm9ds1_api.h
experimental_libraries/LSM9DS1_API.cpp
libraries/lsm9ds1_api.cpp